[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "script-src 'self' https://maps.googleapis.com https://pagead2.googlesyndication.com; object-src 'self'; frame-ancestors 'self'; base-uri 'self';"
